"""
VoltLegal — Response Formatter
Professional formatting, legal citations, disclaimers, rights menus, and IPC/glossary output.
"""

import re

DISCLAIMER = (
    "\n\n⚠️ *Disclaimer:*\n"
    "_This is general legal information only, NOT legal advice. "
    "Always consult a qualified lawyer for your specific situation. "
    "VoltLegal does not replace professional legal counsel._"
)

ANTI_MISUSE_NOTICE = (
    "\n\n🚫 _VoltLegal is designed to help people understand and protect their legal rights. "
    "It does not support, encourage, or assist with any illegal activities._"
)

QUICK_ACTIONS = (
    "\n\n─────────────────────\n"
    "📌 *Quick Actions:*\n"
    "/scan — Upload a legal document or image\n"
    "/situation — Describe your legal situation\n"
    "/draft — Draft a complaint or notice\n"
    "/ipc — Look up IPC/BNS section\n"
    "/glossary — Explain a legal term\n"
    "/rights — Know your rights\n"
    "/hindi — Translate to Hindi\n"
    "/telugu — Translate to Telugu\n"
    "/help — All features & commands"
)


def format_legal_response(raw_text: str, source_label: str = "Groq") -> str:
    """Format an AI-generated legal response for Telegram."""
    if not raw_text or not raw_text.strip():
        return "❌ Sorry, I could not generate a response. Please try again."

    text = raw_text.strip()

    if source_label == "Gemini":
        badge = "📄 *Document Analysis* (via Gemini AI)\n\n"
    else:
        badge = "⚖️ *Legal Analysis* (via VoltLegal AI)\n\n"

    return badge + text + DISCLAIMER + QUICK_ACTIONS


def format_document_analysis(raw_text: str, doc_type: str = "document") -> str:
    """Format document/image analysis response."""
    if not raw_text or not raw_text.strip():
        return "❌ Could not analyze this document. Please ensure the file is clear and readable."

    text = raw_text.strip()
    header = f"📋 *{doc_type.title()} Analysis*\n\n"
    return header + text + DISCLAIMER + QUICK_ACTIONS


def format_situation_response(raw_text: str) -> str:
    """Format situation-help response with extra care notice."""
    if not raw_text or not raw_text.strip():
        return "❌ Sorry, I could not analyze your situation. Please describe it more clearly."

    text = raw_text.strip()
    header = "🛡️ *Situation Analysis & Legal Guidance*\n\n"
    return header + text + DISCLAIMER + ANTI_MISUSE_NOTICE + QUICK_ACTIONS


def format_info_response(raw_text: str) -> str:
    """Format legal information/education response."""
    if not raw_text or not raw_text.strip():
        return "❌ Sorry, I could not find information on that topic. Please try rephrasing."

    text = raw_text.strip()
    header = "📚 *Legal Information*\n\n"
    return header + text + DISCLAIMER + QUICK_ACTIONS


def format_ipc_response(raw_text: str, section: str) -> str:
    """Format IPC section lookup response."""
    if not raw_text or not raw_text.strip():
        return f"❌ Could not find information about Section {section}. Please check the number."

    text = raw_text.strip()
    header = f"📕 *IPC/BNS Section Lookup — {section}*\n\n"
    return header + text + DISCLAIMER + QUICK_ACTIONS


def format_glossary_response(raw_text: str, term: str) -> str:
    """Format glossary term explanation."""
    if not raw_text or not raw_text.strip():
        return f"❌ Could not find the term '{term}'. Please try a different legal term."

    text = raw_text.strip()
    header = f"📖 *Legal Glossary — {term.title()}*\n\n"
    return header + text


def format_draft_response(raw_text: str) -> str:
    """Format a generated legal draft document."""
    if not raw_text or not raw_text.strip():
        return "❌ Could not generate the draft. Please try again with more details."

    text = raw_text.strip()
    header = "📄 *Legal Document Draft*\n\n"
    footer = (
        "\n\n⚠️ *Important:*\n"
        "_This is a DRAFT document generated by AI. "
        "Please review it carefully and consult a lawyer before using it officially. "
        "Verify all details, dates, and legal references._"
    )
    return header + text + footer


def format_voice_transcription(transcription: str) -> str:
    """Format voice message transcription acknowledgment."""
    return f"🎤 *I heard:* _{transcription}_\n\n⚖️ Looking up the law for you..."


def build_welcome_message() -> str:
    """Build the /start welcome message."""
    return (
        "⚖️ *Welcome to VoltLegal* — Your AI Legal Assistant\n\n"
        "I help you understand Indian law in simple language.\n"
        "Tap any command below to get started! 👇\n\n"
        "─────────────────────\n\n"
        "📄 *Scan & Explain*\n"
        "Send a photo, PDF, or Word doc of any legal document and I'll explain it.\n\n"
        "🛡️ *Situation Help* → /situation\n"
        "Tell me what happened — I'll find the laws that protect you.\n\n"
        "📚 *Legal Q&A*\n"
        "Just type any legal question directly!\n\n"
        "✍️ *Draft Documents* → /draft\n"
        "Draft police complaints, legal notices, RTI applications.\n\n"
        "📕 *IPC/BNS Lookup* → /ipc\n"
        "Look up any section (e.g. /ipc 420).\n\n"
        "📖 *Legal Glossary* → /glossary\n"
        "Explain any legal term (e.g. /glossary bail).\n\n"
        "🇮🇳 *Know Your Rights* → /rights\n"
        "Quick reference to your fundamental legal rights.\n\n"
        "🎤 *Voice Messages*\n"
        "Send a voice note — I'll listen and answer!\n\n"
        "🌐 *Hindi Translation* → /hindi\n"
        "Get any response translated to Hindi.\n\n"
        "🌐 *Telugu Translation* → /telugu\n"
        "Get any response translated to Telugu.\n\n"
        "ℹ️ /help  •  /about  •  /feedback\n\n"
        "─────────────────────\n"
        "⚠️ _Legal information only, not legal advice._\n"
        "🚫 _Misuse for illegal purposes is strictly prohibited._"
    )


def build_help_message() -> str:
    """Build the /help message."""
    return (
        "📖 *VoltLegal — How to Use*\n\n"
        "*Commands:*\n"
        "/start — Welcome & feature overview\n"
        "/help — This help message\n"
        "/situation — Start describing a legal situation\n"
        "/draft — Draft a legal document or complaint\n"
        "/ipc `<section>` — Look up an IPC/BNS section\n"
        "/glossary `<term>` — Explain a legal term\n"
        "/rights — Quick reference to your legal rights\n"
        "/hindi — Translate last response to Hindi\n"
        "/telugu — Translate last response to Telugu\n"
        "/clear — Clear current context\n"
        "/cancel — Cancel current conversation\n"
        "/about — About VoltLegal\n"
        "/feedback — Share your feedback\n\n"
        "*Features:*\n"
        "📄 *Send a PDF/Word Doc* → I'll analyze the legal document\n"
        "📷 *Send a Photo* → I'll read and explain any legal notice\n"
        "🎤 *Send a Voice Note* → I'll listen and answer your legal question\n"
        "💬 *Type a question* → I'll explain the relevant law\n"
        "🛡️ */situation* → I'll guide you through your legal situation\n"
        "✍️ */draft* → I'll help you draft complaints, notices, RTI apps\n\n"
        "─────────────────────\n"
        "⚠️ _This bot does not provide legal advice and cannot represent you in court._"
    )


def build_rights_message() -> str:
    """Build the /rights quick-reference message."""
    return (
        "🇮🇳 *Know Your Rights — Quick Reference*\n\n"

        "👮 *When Dealing with Police:*\n"
        "• You have the RIGHT to file an FIR — police cannot refuse (Sec 154 CrPC / Sec 173 BNSS)\n"
        "• You have the RIGHT to remain silent (Article 20(3), Constitution)\n"
        "• Women CANNOT be arrested after sunset and before sunrise (Sec 46(4) CrPC / Sec 35(5) BNSS)\n"
        "• You have the RIGHT to know the grounds of arrest (Article 22(1))\n"
        "• Arrested person MUST be produced before magistrate within 24 hours (Article 22(2))\n"
        "• You have the RIGHT to have a lawyer present during questioning\n\n"

        "🏠 *Tenant Rights:*\n"
        "• Landlord CANNOT evict without legal notice and court order\n"
        "• Landlord CANNOT enter your rented home without permission\n"
        "• Security deposit must be returned within reasonable time after vacating\n"
        "• Unfair rent hike can be challenged under state Rent Control Acts\n\n"

        "💼 *Workplace Rights:*\n"
        "• Sexual harassment complaints → Internal Complaints Committee (POSH Act 2013)\n"
        "• Minimum wages must be paid (Minimum Wages Act / Code on Wages 2019)\n"
        "• Wrongful termination can be challenged under Industrial Disputes Act\n"
        "• Maternity leave — 26 weeks (Maternity Benefit Act 1961)\n\n"

        "🛒 *Consumer Rights:*\n"
        "• Right to file complaint within 2 years (Consumer Protection Act 2019)\n"
        "• File online at consumerhelpline.gov.in or call 1800-11-4000\n"
        "• Right to refund, replacement, or compensation for defective products/services\n\n"

        "📝 *Right to Information:*\n"
        "• Any citizen can file RTI application (RTI Act 2005)\n"
        "• Fee: ₹10 only | Respond within 30 days\n"
        "• File online: rtionline.gov.in\n\n"

        "🏥 *Medical Rights:*\n"
        "• Hospitals CANNOT refuse emergency treatment (Supreme Court ruling)\n"
        "• Right to informed consent before treatment\n"
        "• Medical negligence claims under Consumer Protection Act\n\n"

        "─────────────────────\n"
        "💡 _Want to know more about any right? Just ask me! "
        "Use /ipc to look up specific sections._"
    )


def build_about_message() -> str:
    """Build the /about message."""
    return (
        "⚖️ *About VoltLegal*\n\n"
        "VoltLegal is an AI-powered Indian legal information assistant "
        "that helps common people understand law in simple language.\n\n"
        "*What VoltLegal can do:*\n"
        "• Read and explain legal documents (PDF, images, Word docs)\n"
        "• Analyze your legal situation and suggest applicable laws\n"
        "• Answer legal questions with relevant Acts and sections\n"
        "• Draft legal complaints, notices, and RTI applications\n"
        "• Look up IPC/BNS sections and explain legal terms\n"
        "• Accept voice messages for legal queries\n"
        "• Translate responses to Hindi and Telugu\n\n"
        "*Powered by:*\n"
        "🤖 Groq (LLaMA 3.3 70B) — Legal Q&A & Analysis\n"
        "🤖 Google Gemini 2.5 Flash — Document & Image Reading\n\n"
        "⚠️ _VoltLegal provides legal INFORMATION only. "
        "Always consult a qualified lawyer for legal advice._\n\n"
        "Made with ❤️ for the people of India."
    )
